# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: syclreference.com
subtitle: SYCL Reference Pages
email: morris.hafner@codeplay.com
baseurl: "/syclreference" # the subpath of your site, e.g. /blog
url: "https://mmha.github.io/" # the base hostname & protocol for your site

exclude:
    - "*.sh"
    - vendor # For Travis-CI (see https://jekyllrb.com/docs/continuous-integration/)
    - .bundle

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
